### PR TITLE
CFD-382: Group management HUB : Overview page.

### PR DESCRIPTION
**Pull request by nader77**
#555 

fullscreen_3_29_15__5_41_pm
capacity4more

### CODE REVIEW

**Comment by nader77** [comment]
Update: Added group status and thumbnail image.

* Added an edit link on the group banner as an overlay.

selection_084

**Comment by nader77** [comment]
@zero2one Some questions to finish this issue:

* Could you expand a little about the "Group profile status" ? (Not mentioned in the description).
* Should the "Edit" links on the banner and thumbnail image be in overlay ? (Like seen in the screenshot above ^^)
* Is there a finished design for this page and should we do it in this sprint ?

Thanks.

**Comment by nader77** [comment]
Update: Added access type to the related content title:
capacity4more

**Comment by zero2one** [comment]
@nader77 

#### Could you expand a little about the "Group profile status" ? (Not mentioned in the description).

That is the Group status field.


#### Should the "Edit" links on the banner and thumbnail image be in overlay ? (Like seen in the screenshot above ^^)

Yes


#### Is there a finished design for this page and should we do it in this sprint ?

There is no design for this page.
I will review the pull request and indicate what should changed (if necessary).

**Comment by nader77** [comment]
Thanks. 
But next to the 
Group profile status

It says "70%", is this just a mistake ?

**Comment by zero2one** [comment]
@nader77 
The 70% part is not included for now, see https://issuetracker.amplexor.com/jira/browse/CFD-382.

**Comment by nader77** [comment]
@zero2one @HelenaEksler This is how the manage page looks like now, Tell me if there's any changes needed:
capacity4more

**Comment by nader77** [comment]
Example with related content:
capacity4more

**Comment by HelenaEksler** [comment]
@nader77 Looks fine to me. 
@zero2one Check, please, so we won't miss something.

**Comment by nader77** [comment]
@zero2one Created a custom context for ``OG``.
This one can be used to check the logged in user's permission to to do any action in the group, And for any page.
Removed the custom PHP Code.

**Pull request merged**
