### PR TITLE
[CFM-1410] "New Discussion" button - permissions & styling

### PR DESCRIPTION
**Pull request by guytepper**
https://issuetracker.amplexor.com/jira/browse/CFM-1410

### CODE REVIEW

**Comment by ordavidil** [comment]
@guytepper 
Did you checkout from develop or from Nir's branch ?

**Comment by guytepper** [comment]
@ordavidil Nir's branch.

**Comment by ordavidil** [comment]
So please close this PR and create a new PR comparing to that branch,
thanks.

ps
link between these two.

**Comment by guytepper** [comment]
Closed in favor of #1050

**Pull request closed without merging**
