### PR TITLE
cfd 266 theming theme content detail creation date

### PR DESCRIPTION
**Pull request by jummonk**

### CODE REVIEW

**Comment by jummonk** [comment]
date in discussion teaser
date in event teaser
non recent date in document teaser
recent date in document teaser

**Comment by jummonk** [comment]
date in discussion full

date in discussion full

date in document full

date in document full

date in event full
date in event full

**Comment by jummonk** [comment]
date in wiki full

**Comment by zero2one** [comment]
re-rolled

**Pull request merged**
