### PR TITLE
[CFM-472] notify of new comment on content  - ready for quality check

### PR DESCRIPTION
**Pull request by anvmn**
## This PR is dependent on #1059 

https://issuetracker.amplexor.com/jira/browse/CFM-472

### CODE REVIEW

**Comment by anvmn** [comment]
@ordavidil 
Waiting to be tested, when issue with comment flag is resolved.

**Comment by anvmn** [comment]
out

**Comment by soniCaH** [comment]
Tokens updated: https://issuetracker.amplexor.com/jira/browse/CFM-472

**Comment by anvmn** [comment]
## Replaced by #1189

**Pull request closed without merging**
