### PR TITLE
CFD-310 Homepage : Create new content type "Featured" 

### PR DESCRIPTION
**Pull request by HelenaEksler**
#459

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@amitaibu PR is ready.

1. Created new content type `Featured`
2. Created new custom module `c4m_content_featured`

**Comment by HelenaEksler** [comment]
selection_200

selection_201

**Comment by HelenaEksler** [comment]
@amitaibu  I think we can assign it to Peter?

**Comment by HelenaEksler** [comment]
@nader77 Review this, please.

**Comment by nader77** [comment]
@HelenaEksler Reviewed, assigning to @zero2one .

**Comment by zero2one** [comment]
@HelenaEksler Disable comments for this content type please.

**Pull request merged**
