### PR TITLE
WIP: CFD-294 : Homepage : My Groups (Logged-in users) - theming.

### PR DESCRIPTION
**Pull request by nader77**
#500 
#507
CFD-297: Homepage : Create group list view mode + theming.

### CODE REVIEW

**Comment by nader77** [comment]
Update:
* Added the basic design to my groups.
* Changed the layout of the home-page to 7-5 to be PixelPerfect with the PSD.
* Created a new layout for node view, 3-9 fluid.

**Comment by nader77** [comment]
selection_052

**Comment by nader77** [comment]
Pixel perfect:
selection_054

There is difference in the text, which makes a little bit of difference in the space between the groups.

The collapse/ Expand text:
groups-2015-02-18_14

**Comment by nader77** [comment]
This should not be merged until "Suggested groups" is reviewed and merged, I need to apply this design to that as well, Leaving this for now.

**Comment by nader77** [comment]
Update: Improving Pixel-perfect:
homepage___capacity4more

**Comment by HelenaEksler** [comment]
Isaac Newton user:
selection_228

Admin user:
selection_229

**Comment by nader77** [comment]
Hiding "Show all" link if there are no more groups to show (3 or less groups).

**Comment by nader77** [comment]
I was working on it, It's ok i'm finished i will open a follow up PR.

**Pull request merged**
