### PR TITLE
CFD-291 Homepage : Join. Share. Learn. (Anonymous users) - Theming

### PR DESCRIPTION
**Pull request by HelenaEksler**
#496

### CODE REVIEW

**Comment by HelenaEksler** [comment]
selection_219

**Comment by zero2one** [comment]
Seems that every pulled-in pull request blocks the other pull requests about the home page…

@HelenaEksler Can you re-roll please?

**Comment by HelenaEksler** [comment]
@zero2one Re-rolled.

**Comment by zero2one** [comment]
The theming is not the same as the design provided by Keren…

See https://projects.invisionapp.com/d/main#/console/2556061/57063234/preview

c4m-join share learn

**Comment by HelenaEksler** [comment]
selection_220

**Comment by HelenaEksler** [comment]
selection_221

**Comment by HelenaEksler** [comment]
@zero2one Fixed.

**Pull request merged**
