### PR TITLE
CFM-458: Adds CTA to request membership of private groups

### PR DESCRIPTION
**Pull request by DavidHernandez**
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-458

Button when user requests the membership:
request-membership
Text when the user already has requested the membership and is not approved yet:
membership-pending

### CODE REVIEW

**Comment by DavidHernandez** [comment]
## This issue depends on https://github.com/capacity4dev/capacity4more/pull/1057

**Comment by ordavidil** [comment]
@DavidHernandez 
please re-roll

**Comment by ordavidil** [comment]
@DavidHernandez 
the issue also says:
> User sees a status message: "This is moderated group. Your request is waiting for approval. Continue to explore group X's content"

can you please add a screenshot for that one ?
(or just add the functionality :) )

**Comment by DavidHernandez** [comment]
@ordavidil that is handled in another issue/PR: #1063

**Comment by ordavidil** [comment]
(y)

**Comment by jover** [comment]
Merged CFM-918-join-cta-button manually into develop because this branch was already merged.

**Pull request merged**
