### PR TITLE
CFD-274 : Geo widget : Add arrow logic for 3rd level 

### PR DESCRIPTION
**Pull request by HelenaEksler**
#439

### CODE REVIEW

**Comment by HelenaEksler** [comment]
video5

**Comment by HelenaEksler** [comment]
@amitaibu PR is ready for the code review.

**Comment by zero2one** [comment]
@HelenaEksler Can you do the same in the widget on the quick post form?

c4m-geo-widget

**Comment by HelenaEksler** [comment]
selection_195
selection_196

**Pull request merged**
