### PR TITLE
CFD-306 : Send html mail

### PR DESCRIPTION
**Pull request by zero2one**
### Added dependencies
* Added the mimemail module.
* Added the mailsystem module

### Integration in capacity4more
Added a custom module (c4m_mail) to do the basic configuration of the platform so it supports sending out email in the HTML format.

Added an install hook that replaces all default mail messages by a HTML version of them.

### CODE REVIEW

**Comment by zero2one** [comment]
Ready for review

**Comment by nader77** [comment]
@zero2one Installed and reviewed, all good except I got clipped message to my gmail, Is it something we can fix ? >
selection_044

selection_042

**Comment by zero2one** [comment]
@nader77 Gmail does that if the mail is more then 102KB.
See: https://econsultancy.com/blog/65360-prevent-gmail-clipping-your-message-with-an-email-diet/

It is probably trigged by the css that is to big.

I will put the css on a diet ;-)

**Comment by zero2one** [comment]
@nader77 I remove a lot of fat from the css in the mail.

Can you test again?

**Comment by nader77** [comment]
@zero2one Sorry, Still seeing empty messages (iPhone), Clipped message with link (gmail - PC).
I can see the whole message in the mail client on a mac.

**Comment by zero2one** [comment]
Did you rebuild the theme css before you run the second test?

I just did a new test and I got the message without clipping:

c4m-mail-gmail

**Comment by zero2one** [comment]
The build is broken due to a .info file within the grunt-contrib-imagemin plugin.
Drupal thinks its a theme and tries to add it to the system table.

The file path is to long and does not fit within the filename field.

**Pull request merged**
