### PR TITLE
CFD-526 : Wiki : Add functionality to rearrange book pages

### PR DESCRIPTION
**Pull request by solker**
https://issuetracker.amplexor.com/jira/browse/CFD-526

### CODE REVIEW

**Comment by solker** [comment]
Its looking that draggableviews_books not working on drupal 7. Impossible to display wiki pages in hierarchical view.

**Comment by zero2one** [comment]
@solker  needs a re-roll to fix the broken build

**Comment by solker** [comment]
@zero2one re-rolled. Waiting Travis.

**Comment by zero2one** [comment]
Replaced by #763

**Pull request closed without merging**
