### PR TITLE
CFD-529 : Fix upload documents.

### PR DESCRIPTION
**Pull request by nader77**
Also:
* fixed some permission issue in RESTful, Projects has no ``c4m_og_status``.
* There was an error uploading files because of no "create files" permissions.

### CODE REVIEW

**Comment by nader77** [comment]
@zero2one PR is ready.

**Comment by zero2one** [comment]
@nader77 It is fixed for an platform administrator.

But not for a group owner/group admin or group member.

c4m-comment-document-owner

**Comment by zero2one** [comment]
@nader77 build is broken & still [not working for non-group administrators](#issuecomment-108846804).

**Comment by soniCaH** [comment]
PR closed
Diff added to JIRA ticket https://issuetracker.amplexor.com/jira/browse/CFM-1050 to be fixed in new phase.

**Pull request closed without merging**
