### PR TITLE
CFD-531 Manage group categories: New group has no buttons to start adding categories

### PR DESCRIPTION
**Pull request by nader77**
https://issuetracker.amplexor.com/jira/browse/CFD-531

### CODE REVIEW

**Comment by nader77** [comment]
Fixes workflow:
new-cats

**Comment by nader77** [comment]
@HelenaEksler PR is ready for code review.

**Comment by HelenaEksler** [comment]
@nader77 Looks good.

**Comment by HelenaEksler** [comment]
@MPParsley PR is ready for review.

**Pull request merged**
