### PR TITLE
CFD-350 : About group details

### PR DESCRIPTION
**Pull request by soniCaH**
See https://issuetracker.amplexor.com/jira/browse/CFD-350 for remark

### CODE REVIEW

**Comment by zero2one** [comment]
h3. Missing link
Can you add also the Manage this group link (next to the group access type) in the sidebar.

It needs to point to <group-purl-path>/manage and is only available for Platform Admins (have manage content rights), Group owners & Group administrators.

c4m-manage-group


h3. Missing labels
Can you add the missing labels in the "More Details" section in the sidebar:

See https://projects.invisionapp.com/d/main#/console/1420103/40189685/preview

* Topics
* Regions & Countries

c4m-manage-group-wf

**Comment by soniCaH** [comment]
screen shot 2015-04-20 at 17 55 17

**Comment by soniCaH** [comment]
screen shot 2015-04-27 at 08 36 26

**Comment by soniCaH** [comment]
Wrong member count:
skitch

Fixed with entity_filter:
screen shot 2015-04-27 at 09 01 10

**Pull request merged**
