### PR TITLE
CFD-396 Organisations & Email domains : Refactor Restricted groups to support the organisations & email domains

### PR DESCRIPTION
**Pull request by HelenaEksler**
#593 
Follows up #594

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@nader77 Can you re-roll and change pulggable node access version to dev (All is already on Drupal.org).

**Comment by nader77** [comment]
Waiting for #566 to be merged to fix the behat test.

**Comment by HelenaEksler** [comment]
@nader77  @amitaibu Could you review this, please?

**Comment by nader77** [comment]
@HelenaEksler Ready for me.

**Comment by zero2one** [comment]
Bug in Travis-CI : all individual builds passes but Travis says total result failed…

**Pull request merged**
