### PR TITLE
[CFM-1067] Rework Event overview page view

### PR DESCRIPTION
**Pull request by soniCaH**
https://issuetracker.amplexor.com/jira/browse/CFM-1067

screen shot 2016-11-22 at 11 03 08

screen shot 2016-11-22 at 11 03 21

### CODE REVIEW

**Comment by anvmn** [comment]
@ordavidil 
The title of events/upcoming page seem to be incorrect:
selection_163

**Comment by ordavidil** [comment]
@anvmn 
for the last comment on JIRA, see this:
https://github.com/capacity4dev/capacity4more/pull/1570/files#diff-8da6f241e44207038d43db183f3e2faaR51

**Comment by anvmn** [comment]
**Global events view:**
selection_168

**Upcoming events view:**
selection_167

**Passed events view:**
selection_168

**Comment by ordavidil** [comment]
@anvmn 
please re-roll

**Comment by anvmn** [comment]
**Global events view:** 
selection_169

**Pull request merged**
