### PR TITLE
[CFM-932] Removing the events and documents from the quickpost.

### PR DESCRIPTION
**Pull request by ordavidil**
https://issuetracker.amplexor.com/jira/browse/CFM-932

### CODE REVIEW

**Comment by ordavidil** [comment]
@nader77 
can you review this one please ?
thanks ...

**Comment by nader77** [comment]
@ordavidil Please add screenshots of the updated quick-post :)

**Comment by nader77** [comment]
@ordavidil I think there's no point of having the discussion button if it's the only option, what do you think ?

**Comment by ordavidil** [comment]
@nader77 
True, but i think that since the logic is already implemented then it's better not to touch for now, we can handle it under https://issuetracker.amplexor.com/jira/browse/CFM-933

**Comment by ordavidil** [comment]
selection_256

**Pull request merged**
