### PR TITLE
CFD-402 Manage group features

### PR DESCRIPTION
**Pull request by MPParsley**
Added listing of enabled/disabled features in a group.

manage dashboard features

### CODE REVIEW

**Comment by MPParsley** [comment]
Added management page for group features (CFD-401).

manage group features status explanation
manage group features

**Comment by zero2one** [comment]
This page should be rendered using the front-end theme.

The path should be <group-purl-path>/manage/features

**Comment by MPParsley** [comment]
Themed manage group features form in front end theme.

manage group features enabled

manage group features disabled

**Comment by MPParsley** [comment]
We could optionally do it in an overlay (cfr manage video) if that is desired.

**Comment by MPParsley** [comment]
A default argument handler c4m_og_features_argument_default_enabled is implemented to list the enabled content types in a group.

Note: Make sure to check "Allow multiple values" when using this default argument.

default argument features enabled content types

**Comment by zero2one** [comment]
@MPParsley Needs a reroll

**Pull request merged**
