### PR TITLE
[CFM-924-fix] Related groups/projects views CSS adjustments & related projects view filtering.

### PR DESCRIPTION
**Pull request by anvmn**
https://issuetracker.amplexor.com/jira/browse/CFM-924

### CODE REVIEW

**Comment by anvmn** [comment]
selection_141

**Comment by ordavidil** [comment]
@anvmn 
On her last comment on [CFM-1134](https://issuetracker.amplexor.com/jira/browse/CFM-1134), Diane said:
> The related groups and related projects are appearing with a styling error. For projects, this was reported yesterday under [CFM-924](https://issuetracker.amplexor.com/jira/browse/CFM-1134)
We also see the same incorrect display for groups as shown beloew:
image


Does this PR is handling that as well ?

**Comment by anvmn** [comment]
@ordavidil 
CFM-924 describes requirements for 'related projects' view on group dashboard.
This PR deals only with 'related projects' view.

**Comment by ordavidil** [comment]
@anvmn 
both issues seems related,
is it easily possible to handle the other one here as well ?  (probably only need to add a class somewhere in the scss file)

**Comment by anvmn** [comment]
@ordavidil 
Yes, small update at CSS views file.
Won't take more than 5 minutes...

**Comment by anvmn** [comment]
selection_143

**Pull request merged**
