### PR TITLE
[CFM-1030] -Implement group dashboard invite member CTA

### PR DESCRIPTION
**Pull request by ybaras**
https://issuetracker.amplexor.com/jira/browse/CFM-1030

### CODE REVIEW

**Comment by ybaras** [comment]
**Invite link CTA:**

invite-btn

**Comment by ordavidil** [comment]
@ybaras 
please attach a screenshot while you're not the admin ...  thanks

**Comment by ybaras** [comment]
cfm-1030

**Comment by ordavidil** [comment]
@ybaras 
please re-roll

**Pull request closed without merging**
