### PR TITLE
CFD-268 : Quick Post : Add option to replace the uploaded file 

### PR DESCRIPTION
**Pull request by HelenaEksler**
#418

### CODE REVIEW

**Comment by HelenaEksler** [comment]
video1

**Comment by HelenaEksler** [comment]
@amitaibu PR is ready for review

**Comment by HelenaEksler** [comment]
@amitaibu Can I assign this to Peter?

**Comment by zero2one** [comment]
Could you add more info to it (and format) like in the designs & wireframe?

* [Design](https://projects.invisionapp.com/d/main#/console/1420103/46871445/preview)
* [Wireframe](https://projects.invisionapp.com/d/main#/console/1420103/33869533/preview)

**Comment by HelenaEksler** [comment]
selection_179

**Pull request merged**
