### PR TITLE
CFD-594 Taxonomy widgets : search taxonomies do not display sub-level data

### PR DESCRIPTION
**Pull request by HelenaEksler**
https://issuetracker.amplexor.com/jira/browse/CFD-594

### CODE REVIEW

**Comment by HelenaEksler** [comment]
Workflow:
taxonomy

**Comment by zero2one** [comment]
@HelenaEksler needs a re-roll to fix the broken build

**Comment by HelenaEksler** [comment]
@nader77 Please, review this

**Comment by nader77** [comment]
@HelenaEksler Looks good.

**Comment by zero2one** [comment]
### Filtering leads to empty checkbox labels

Scenario:
* Open a form with the Regions & Countries widget.
* Click on the Regions & Countries taxonomy button
* Start typing "is" in the search box
* Click on the "Africa" region
* There is an empty checkbox label between "Northern Africa" and "Western Africa"

c4m-taxonomy-widget

**Comment by HelenaEksler** [comment]
selection_344
Fixed.

**Pull request merged**
