### PR TITLE
CFD-325 Missing asterisk in the Group creation form 

### PR DESCRIPTION
**Pull request by HelenaEksler**
#610

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@zero2one @MPParsley  Can you look at this PR. I've added more fields of group creation to required as asked. And I had to add filling of these fields in tests. And here is the problem.
I can't find the reason why ``$step[] = new Step\When('I fill field message to site admin with "This is default message to admin."');`` is not working (It's inside [Group creation](https://github.com/capacity4dev/capacity4more/pull/611/files#diff-0190a18d49a8dddf5bae8f4f1646aa4eR143) step). The strangest thing that if this step is used separately - it's working (see test [Test](https://github.com/capacity4dev/capacity4more/pull/611/files#diff-8d254d499dc22d6df99234a0694d95c0R77)). Maybe I'm missing something.

**Comment by MPParsley** [comment]
@HelenaEksler 
    // This is the required banner
    $steps[] = new Step\When('I attach the file to the field banner');

    // This is the required message to admin.
    $step[] = new Step\When('I fill field message to site admin with "This is default message to admin."');

=> should be
    $steps[] = new Step\When('I fill field message to site admin with "This is default message to admin."');

good luck!

**Comment by HelenaEksler** [comment]
request_group___capacity4more-3

@zero2one PR is ready for review.

**Comment by MPParsley** [comment]
@HelenaEksler,

Could you:
- apply t() function on strings
- fix the warning "field is required" when no topic is selected

**Comment by HelenaEksler** [comment]
selection_307

@MPParsley PR is ready.

**Comment by MPParsley** [comment]
Looks good, can be merged when tests succeed.

**Comment by SebastienVanRintel** [comment]
@MPParsley 
The field error shows the correct text (ex. Group topics field is required.) but the asterix/star still isn't shwoing red.
Do I need to look further on this?

**Pull request merged**
