### PR TITLE
CFD-413: White screen of death after deleting discussion

### PR DESCRIPTION
**Pull request by solker**
#576

### CODE REVIEW

**Comment by nader77** [comment]
@solker What's the status of this PR ? Add a screenshot and assign to me if it's ready.

**Comment by solker** [comment]
@nader77 need rewrite a logic of app. Need discuss with c4m.

**Comment by solker** [comment]
Update: There's actually already code in message that deals with this deletion, so I'll check why doesn't kick-in.

`admin/config/system/message`

selection_002

**Comment by solker** [comment]
Message module updated to 1.10.
Also updated configuration then all messages removed automatically when node removed.

**Comment by amitaibu** [comment]
Great. Needs a re-roll

**Comment by solker** [comment]
Title and Body required by default in any mode. 
Re-rolled. 

selection_003

**Comment by HelenaEksler** [comment]
@solker Looks fine. It's worth to add video of the workflow.

**Pull request merged**
