### PR TITLE
Document view mode for library in overlay.

### PR DESCRIPTION
**Pull request by HelenaEksler**

### CODE REVIEW

**Comment by HelenaEksler** [comment]
selection_155

**Comment by HelenaEksler** [comment]
@amitaibu PR is ready.

1. Widget is moved from content_discussion to the own module.
2. Created new view mode for documents in the library.

Here is the workflow:
doc_widget5

**Comment by amitaibu** [comment]
@HelenaEksler you can merge squash to ``develop-widgets``

**Comment by HelenaEksler** [comment]
Merged.

**Pull request closed without merging**
