### PR TITLE
CFD-299 & CFD-300 : Group members

### PR DESCRIPTION
**Pull request by jummonk**
...de for group members will reside

### CODE REVIEW

**Comment by soniCaH** [comment]
screen shot 2015-02-11 at 15 12 56
screen shot 2015-02-11 at 15 12 53
screen shot 2015-02-11 at 15 12 48
screen shot 2015-02-11 at 15 12 44

**Comment by jummonk** [comment]
members

**Comment by soniCaH** [comment]
Demo content updated with pending members, group administrators...

screen shot 2015-02-16 at 14 14 27

**Comment by zero2one** [comment]
Finished functionality:

## Themed List view

* Themed name.
* Themed list style switchers (icons).
* Added sorts

c4m-members-list

## Themed Table view
* Themed name.
* Themed list style switchers (icons).
* Added sorts

c4m-members-table

## Support for mobile view ports (table view)
c4m-members-mobile


## Contact group members
c4m-members-contact

**Pull request merged**
