### PR TITLE
CFM-1206 Implement CTA hook for group actions (in develop)

### PR DESCRIPTION
**Pull request by jover**
Replaces PR #1073

https://issuetracker.amplexor.com/jira/browse/CFM-1206

### CODE REVIEW

**Comment by ordavidil** [comment]
@DavidHernandez 
can you please fix travis issues ?

**Comment by DavidHernandez** [comment]
## Merge first https://github.com/capacity4dev/capacity4more/pull/1120

**Comment by ordavidil** [comment]
@DavidHernandez 
Can you please add (3) screenshots ?

**Comment by DavidHernandez** [comment]
@ordavidil, better styling can be found on the related issue with screenshots of how it looks: https://github.com/capacity4dev/capacity4more/pull/1120
Desktop:
desktop-cta
Tablet:
cta-tablet
Mobile:
mobile-cta

**Pull request merged**
