### PR TITLE
CFD-360 Voices & Views overview

### PR DESCRIPTION
**Pull request by MPParsley**
Overview page of all Voices & Views:
- A search view
- Only published Voices & Views
- Order by post date (desc) by default
- Showing teasers
- Paged, 10 items per page.

voices views overview

### CODE REVIEW

**Comment by MPParsley** [comment]
Added filter on topics.
Show title on top.

voices views

**Comment by MPParsley** [comment]
Demo articles

voices views demo content

**Comment by zero2one** [comment]
@MPParsley 

Voices & Views overview:
* There is a missing list image for the "article/millennium-windmill-development-and-modern-engineering" article.

Groups overview : 
* Filter : the filter should show "My Groups" filter only when the user has groups (do not count projects).

**Comment by MPParsley** [comment]
Fixed the image and added API calls to get groups for a user and that make the difference between projects & groups.

**Pull request merged**
