### PR TITLE
CFD-473 missing first last pagination

### PR DESCRIPTION
**Pull request by SebastienVanRintel**
Pager proposal:
image

image

### CODE REVIEW

**Comment by MPParsley** [comment]
All features are now in default state after a new deploy:

$ drush @c4m fd
 Name                                  Feature                          Status    Version      State
 Admin Groups                          c4m_admin_groups                 Enabled   7.x-1.0
 Admin Organisations                   c4m_admin_organisations          Enabled   7.x-1.0
 Comment                               c4m_comment                      Enabled
 Article content type                  c4m_content_article              Enabled   7.x-1.x-dev
 Group banner content type             c4m_content_banner               Enabled   7.x-1.0-dev
 Book content type                     c4m_content_book                 Enabled   7.x-1.x-dev
 Discussion content type               c4m_content_discussion           Enabled   7.x-1.x-dev
 Document content type                 c4m_content_document             Enabled   7.x-1.x-dev
 Event content type                    c4m_content_event                Enabled   7.x-1.x-dev
 Featured content type                 c4m_content_featured             Enabled   7.x-1.0-dev
 Group content type                    c4m_content_group                Enabled   7.x-1.0-dev
 In the Picture content type           c4m_content_inthe_picture        Enabled   7.x-1.0-dev
 Organisation content type             c4m_content_organisation         Enabled   7.x-1.0-dev
 Page element content type             c4m_content_page_element         Enabled   7.x-1.0-dev
 Photo content type                    c4m_content_photo                Enabled   7.x-1.x-dev
 Photo Album content type              c4m_content_photoalbum           Enabled   7.x-1.x-dev
 Project content type                  c4m_content_project              Enabled   7.x-1.x-dev
 Region content type                   c4m_content_region               Enabled   7.x-1.x-dev
 Task content type                     c4m_content_task                 Enabled   7.x-1.x-dev
 Task List content type                c4m_content_tasklist             Enabled   7.x-1.x-dev
 Topic content type                    c4m_content_topic                Enabled   7.x-1.x-dev
 Wiki page content type                c4m_content_wiki_page            Enabled   7.x-1.x-dev
 Fields Demo                           c4m_demo_fields                  Disabled  7.x-1.x-dev
 Document widget                       c4m_document_widget              Enabled
 Custom Display Suite functionalities  c4m_ds                           Enabled   7.x-1.x-dev
 Homepage                              c4m_features_homepage            Enabled
 Homepage Intro video                  c4m_features_homepage_intro      Enabled
 In the Pictures overviews             c4m_features_inthe_picture       Enabled   7.x-1.0
 Discussions                           c4m_features_og_discussions      Enabled   7.x-1.x-dev
 Documents                             c4m_features_og_documents        Enabled   7.x-1.x-dev
 Events                                c4m_features_og_events           Enabled   7.x-1.x-dev
 Group Dashboard                       c4m_features_og_group_dashboard  Enabled   7.x-1.x-dev
 Highlights                            c4m_features_og_highlights       Enabled   7.x-1.x-dev
 Group Management                      c4m_features_og_manage           Enabled   7.x-1.0
 Members                               c4m_features_og_members          Enabled   7.x-1.x-dev
 Tasks overview                        c4m_features_og_overview_tasks   Enabled   7.x-1.x-dev
 Task lists                            c4m_features_og_tasklists        Enabled   7.x-1.x-dev
 Articles Overview                     c4m_features_overview_articles   Enabled   7.x-1.x-dev
 Events overview                       c4m_features_overview_events     Enabled   7.x-1.x-dev
 Groups overview                       c4m_features_overview_groups     Enabled   7.x-1.x-dev
 People overview                       c4m_features_overview_people     Enabled   7.x-1.x-dev
 Projects overview                     c4m_features_overview_projects   Enabled   7.x-1.x-dev
 Regions overview                      c4m_features_overview_regions    Enabled   7.x-1.x-dev
 Topics overview                       c4m_features_overview_topics     Enabled   7.x-1.x-dev
 Body Field                            c4m_field_body                   Enabled   7.x-1.x-dev
 Date field                            c4m_field_date                   Enabled   7.x-1.x-dev
 Link Fields                           c4m_field_link                   Enabled
 Location Field                        c4m_field_location               Enabled   7.x-1.x-dev
 Media field                           c4m_field_media                  Enabled   7.x-1.x-dev
 Money Field                           c4m_field_money                  Enabled   7.x-1.x-dev
 Group fields                          c4m_field_og                     Enabled   7.x-1.x-dev
 Related Organic Groups                c4m_field_related_og             Enabled   7.x-1.x-dev
 Related users field                   c4m_field_user                   Enabled   7.x-1.x-dev
 Date Helper                           c4m_helper_date                  Enabled
 Mail                                  c4m_mail                         Enabled   7.x-1.x-dev
 Message                               c4m_message                      Enabled
 Organic Group Functionality           c4m_og                           Enabled   7.x-1.x-dev
 Group Menu                            c4m_og_menu                      Enabled   7.x-1.x-dev
 Search                                c4m_search                       Enabled   7.x-1.x-dev
 Search Content                        c4m_search_nodes                 Enabled   7.x-1.x-dev
 User                                  c4m_user                         Enabled   7.x-1.x-dev
 User Profile Bar                      c4m_user_bar                     Enabled   7.x-1.x-dev
 User Profile                          c4m_user_profile                 Enabled   7.x-1.x-dev
 Date vocabulary                       c4m_vocab_date                   Enabled
 Document Type vocabulary              c4m_vocab_document_type          Enabled
 Regions & Countries vocabulary        c4m_vocab_geo                    Enabled   7.x-1.x-dev
 Language vocabulary                   c4m_vocab_language               Enabled
 Vocabulary widget                     c4m_vocab_widget                 Enabled
 Date Migration Example                date_migrate_example             Disabled  7.x-2.8
 Features Tests                        features_test                    Disabled  7.x-2.3
 Message example                       message_example                  Disabled  7.x-1.9
 Message notify example                message_notify_example           Disabled  7.x-2.5
 Message OG example                    message_og_example               Disabled  7.x-1.9
 migrate_example_baseball              migrate_example_baseball         Disabled  7.x-2.5
 Migrate example - Oracle              migrate_example_oracle           Disabled  7.x-2.5
 Migrate Extras Media                  migrate_extras_media             Disabled  7.x-2.5
 Migrate Extras Pathauto Example       migrate_extras_pathauto          Disabled  7.x-2.5
 OG example                            og_example                       Disabled

**Comment by MPParsley** [comment]
@SebastienVanRintel, can you fix the Scrutinizer issues?

**Comment by SebastienVanRintel** [comment]
@MPParsley , the scruntinizer issues are solved

**Comment by kerensoref** [comment]
Like so?
first last

**Pull request merged**
