### PR TITLE
CFD-158: Full form : Wiki page.

### PR DESCRIPTION
**Pull request by HelenaEksler**
#353 
Follows up https://github.com/capacity4dev/capacity4more/pull/357

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@zero2one What about this PR?

**Comment by zero2one** [comment]
The tags field is not yet in the proper spot.

c4m-wiki-page-full-form

**Comment by HelenaEksler** [comment]
After re-rolling fields are in the right places.

selection_165

**Comment by zero2one** [comment]
Travis Build broke.

Is it a hick-up in Travis, will a rerun fix it?

**Comment by HelenaEksler** [comment]
I'm sure it will pass if rerun. I've seen such an error before.

**Comment by amitaibu** [comment]
I've clicked on re-run

**Comment by HelenaEksler** [comment]
Test is green now.

**Pull request merged**
