### PR TITLE
CFD-450 check box in document create full form should not be

### PR DESCRIPTION
**Pull request by HelenaEksler**
https://issuetracker.amplexor.com/jira/browse/CFD-450

### CODE REVIEW

**Comment by HelenaEksler** [comment]
video19

**Comment by HelenaEksler** [comment]
Add to library by default (user doesn't see the field in document creation form).
selection_320

**Comment by HelenaEksler** [comment]
@nader77 Review, please.

**Comment by nader77** [comment]
@HelenaEksler Looks good, Assigned to Peter.

**Pull request merged**
