### PR TITLE
CFD-309 : Homepage : Add extra Voices & views fields needed for the carousel

### PR DESCRIPTION
**Pull request by nader77**
#465 
The four fields:
* intro text 
* wide banner image
* checkbox to promote to carroussel (= default Drupal "Promote to front").
* checkbox to switch on/off stickyness (= default Drupal "Sticky").

selection_028

### CODE REVIEW

**Comment by nader77** [comment]
@amitaibu PR is ready for code review.

**Comment by nader77** [comment]
@HelenaEksler PR is ready.

**Comment by nader77** [comment]
@HelenaEksler Please review this.

**Comment by HelenaEksler** [comment]
@nader77 Looks good.

**Pull request merged**
