### PR TITLE
CFD-506 : document is not a mandatory field

### PR DESCRIPTION
**Pull request by solker**
https://issuetracker.amplexor.com/jira/browse/CFD-506

@nader77 done, ready for code review. 

selection_025

selection_026

### CODE REVIEW

**Comment by nader77** [comment]
@solker Looks good, When tests are green assign to Peter.

**Comment by nader77** [comment]
@solker Please fix tests.

**Comment by solker** [comment]
@nader77 behat test is fail because upload file via a full form is not working. I already made issue about it - https://issuetracker.amplexor.com/jira/browse/CFD-535.

**Comment by nader77** [comment]
@solker We can't merge a branch with failing tests, Put the tests in ``wip`` tag or something like that. This needs to be green.

**Comment by zero2one** [comment]
@solker  needs a re-roll to fix the broken build

**Comment by solker** [comment]
@zero2one re-rolled. Waiting Travis.

**Comment by nader77** [comment]
@solker I will fix the travis tests.

**Comment by nader77** [comment]
@HelenaEksler Isn't the whole point of this PR is to make the field required ?

**Comment by HelenaEksler** [comment]
@nader77 I was checking tests.

**Comment by HelenaEksler** [comment]
@nader77 Check, please. Had to comment tests about uploading files to document. But field is mandatory now.

**Comment by nader77** [comment]
@HelenaEksler Should we delete the added functions in behat if we are not gonna use them ?

**Comment by nader77** [comment]
@HelenaEksler We still using the function in the test that is not commented, So all is good.

**Pull request merged**
