### PR TITLE
CFD-587 : Group Status : Show status label on overview pages.

### PR DESCRIPTION
**Pull request by nader77**
https://issuetracker.amplexor.com/jira/browse/CFD-587

### CODE REVIEW

**Comment by nader77** [comment]
Status in the display modes:
teaser:
selection_130

Dashboard:
selection_131

Teaser list:
selection_132

**Comment by nader77** [comment]
@HelenaEksler Please review.

**Comment by HelenaEksler** [comment]
@nader77 Looks good.
@zero2one Pr is ready for review.

**Comment by zero2one** [comment]
@nader77 Needs a re-roll.

**Pull request merged**
