### PR TITLE
CFD-595 Document Library : Use smaller image preview when uploading an image as attachment to group content

### PR DESCRIPTION
**Pull request by HelenaEksler**
https://issuetracker.amplexor.com/jira/browse/CFD-595

### CODE REVIEW

**Comment by HelenaEksler** [comment]
Origial file:
gizra

Preview with style "Small":
selection_341

Preview for non-image file:
selection_342

**Comment by HelenaEksler** [comment]
@zero2one Isn't it better to use the "Medium" style for image files?
Preview with style "Medium":
selection_343

**Comment by zero2one** [comment]
@HelenaEksler Medium is ok.

The preview needs only to be replaced for images.
The style (small icon + filename) was ok for non images.

**Comment by HelenaEksler** [comment]
@zero2one I added this screenshot to show, that other document preview is not broken. I'll change style to "medium".

**Pull request merged**
