### PR TITLE
CFD-527: Navigation theming

### PR DESCRIPTION
**Pull request by soniCaH**

### CODE REVIEW

**Comment by soniCaH** [comment]
Main navigation

screen shot 2015-05-18 at 09 24 27

Main navigation (mobile)
screen shot 2015-05-18 at 09 24 20

Group navigation
screen shot 2015-05-18 at 09 24 50

Group navigation (mobile)
screen shot 2015-05-18 at 09 24 58

**Comment by soniCaH** [comment]
By default Drupal has the user-menu (my account, logout) set as the secondary navigation menu, appearing under/next to the main navigation.

Since this is not mentioned on the designs, I unset this.

**Comment by soniCaH** [comment]
I need to re-add the user-menu to the page template.
Behat (and simpletest) use the visual "Log out" link to detect if a user is logged in or not. Removing the menu makes the tests fail.
Added below the main menu (default placing) until a design is created.

**Comment by MPParsley** [comment]
@soniCaH, is it possible to:
- add some left margin in the mobile view
- make sure the items remain on one line

schermafdruk 2015-05-18 16 29 58
schermafdruk 2015-05-18 16 30 28

**Comment by soniCaH** [comment]
Padding was set to 10px, set it to 20px now (mobile)
Lowered font-size and margings on smaller screens to fit on one line.

**Comment by zero2one** [comment]
@soniCaH  needs a re-roll to fix the broken build

**Comment by soniCaH** [comment]
Re-rolling

**Pull request merged**
