### PR TITLE
CFM-1132-Removing the read more link on the About this group block.

### PR DESCRIPTION
**Pull request by ordavidil**
* Before:

selection_178

* After:

selection_179

### CODE REVIEW

**Comment by nader77** [comment]
@soniCaH Ready for code review.

**Comment by soniCaH** [comment]
@nader77 can you please assign the JIRA tickets if they're completely finished? It's hard to manage JIRA + GH

**Comment by ordavidil** [comment]
@soniCaH 
The [ticket](https://issuetracker.amplexor.com/jira/browse/CFM-1132) on JIRA is not done yet, this PR is a partial of it.

**Comment by nader77** [comment]
Ok we will keep it assigned to me until the whole Jira issue is ready.

**Comment by ordavidil** [comment]
selection_189

**Comment by soniCaH** [comment]
Please update theming and labels:

- About this group => About the group
- Group created on: [date] => Group created on [date]
- Dashed line above/beneath "group created on"
- Center align  "group created on"

**Comment by ordavidil** [comment]
@soniCaH 

As you can see in the [design](https://wiki.amplexor.com/confluence/pages/viewpage.action?pageId=116101181):
selection_190

* It says "about this page"
* There is no dashed line above/beneath
* The text is not centered aligned

About the `:`, this is generated automatically by the display of the field, I'll need to override it in a specific function, and I'll need you to add more time for the estimation.

**Comment by soniCaH** [comment]
@ordavidil That's the wireframe; note that designs are created for the group dashboard: https://wiki.amplexor.com/confluence/display/C4DNG/Design+group+home+page

Removing the colon is simply changing the template to Display Suite expert and checking the checkbox

**Comment by ordavidil** [comment]
@soniCaH 
Would've been super helpful if that was the link on the task in JIRA and not the link to the wireframe 
:\

**Comment by soniCaH** [comment]
@ordavidil There's a link on that page to notify there's a design. During the kick-offs we had we also mentioned there are limited designs for the main landing page + the group dashboard.
Wireframes are always referenced because they defined the functional behaviour. Nonetheless sorry for this miscommunication.

**Comment by ordavidil** [comment]
It's ok,
here is a screenshot after the fix:
selection_191


I believe there is a different task that should take care of the "manage this group" link, right ?

**Comment by soniCaH** [comment]
Yes indeed

**Comment by ordavidil** [comment]
@soniCaH 
Green :)

**Comment by soniCaH** [comment]
@ordavidil merged :D

**Pull request merged**
