### PR TITLE
CFD-154 - Group dashboard: recent members overview

### PR DESCRIPTION
**Pull request by soniCaH**

### CODE REVIEW

**Comment by soniCaH** [comment]
screen shot 2015-01-16 at 14 25 13

**Comment by soniCaH** [comment]
screen shot 2015-01-16 at 14 34 34

**Comment by soniCaH** [comment]
(side-effect: members overview has basic "theming" and initials as well):

screen shot 2015-01-16 at 14 40 37

**Comment by zero2one** [comment]
YES!

**Pull request merged**
