### PR TITLE
CFD-370: In the picture : Add blocks above overview pages.

### PR DESCRIPTION
**Pull request by nader77**
#540

### CODE REVIEW

**Comment by nader77** [comment]
UPDATE: I have added blocks to the existing overview pages:

## People:
selection_071

## Events:

#### Upcoming:
selection_072

#### Past:
selection_073

This PR needs the overview pages PRs to be merged first.

**Comment by HelenaEksler** [comment]
@nader77 We should not limit items. It's responsibility of the site admin to remove (unpublish unneeded items).

**Comment by nader77** [comment]
@zero2one Please review this and then i will add the overview contexts when all the overview PRs are merged.

**Comment by nader77** [comment]
Update: Added "In the picture" block to the "Group" overview page:
selection_078

**Comment by nader77** [comment]
Update: Added "In the picture" block to the "Voices & Views" overview page:
selection_084

**Comment by nader77** [comment]
@zero2one 2 questions.

- Only the "Projects" overview page is missing, Is there an Issue to create it like the rest ?
- Is there a design for "In the picture" blocks on the overview pages ? (For now as you can see in the screenshots is just a wide picture with description and the link underneath it).

Thanks.

**Comment by zero2one** [comment]
Don't mind the projects page yet ;-)

**Comment by zero2one** [comment]
The text should be shown in an overlay
+ The whole banner should be clickable.

Needs to be fixed later…

**Pull request merged**
