### PR TITLE
CFD-225 - Theme comment stream

### PR DESCRIPTION
**Pull request by soniCaH**

### CODE REVIEW

**Comment by soniCaH** [comment]
screen shot 2015-01-06 at 11 42 15

**Comment by soniCaH** [comment]
screen shot 2015-01-06 at 11 46 18

**Comment by zero2one** [comment]
Comments in Activity Stream:

The content title should link to the comment (anchor on the content detail page).

c4m-activity-comment-link

**Comment by zero2one** [comment]
needs a re-roll

**Comment by soniCaH** [comment]
Re-rolled + updated to link to the comment directly

**Pull request merged**
