### PR TITLE
CFD-592 : Document Library : Theme the document list below group content detail pages.

### PR DESCRIPTION
**Pull request by nader77**
https://issuetracker.amplexor.com/jira/browse/CFD-592

### CODE REVIEW

**Comment by nader77** [comment]
discussion-documents

**Comment by nader77** [comment]
@HelenaEksler Please review.

**Comment by nader77** [comment]
@zero2one The documents in events has a very different view than discussions, Should I theme them the same as the ones in Discussions ? 
an_old_nobel_prize_event___capacity4more

**Comment by zero2one** [comment]
They should be themed the same way as on the discussion detail page.

But: keep the grouping by type (Agenda & Information, Presentation, Additional, …)

**Comment by nader77** [comment]
Documents in events:
selection_134

Documents is discussions:
selection_133

**Comment by nader77** [comment]
@zero2one PR is ready for code review.

**Comment by zero2one** [comment]
@nader77 needs a re-roll.

**Comment by zero2one** [comment]
Can't be tested as long as #767 is not fixed…

**Pull request merged**
