### PR TITLE
CFD-512 : Move c4m_banner field to a separate module.

### PR DESCRIPTION
**Pull request by nader77**
https://issuetracker.amplexor.com/jira/browse/CFD-512

### CODE REVIEW

**Comment by nader77** [comment]
Field:
selection_121
Image style:
selection_120

**Comment by nader77** [comment]
@HelenaEksler PR is ready for code review.

**Comment by HelenaEksler** [comment]
@nader77 Looks good.

**Comment by HelenaEksler** [comment]
@MPParsley PR is ready for review.

**Pull request merged**
