### PR TITLE
CFM-1238 Implement group status flow

### PR DESCRIPTION
**Pull request by DavidHernandez**
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1238

### CODE REVIEW

**Comment by DavidHernandez** [comment]
## Depends on https://github.com/capacity4dev/capacity4more/pull/1026

**Comment by ordavidil** [comment]
@DavidHernandez 
can you add a gif for that flow that shows the status of the group ?

**Comment by DavidHernandez** [comment]
out

**Comment by jover** [comment]
This PR was merged into `feature/CFM-1294`, but that PR was already merged into `develop` so I did a manual merge in order to move this PR into `develop`.

**Pull request merged**
