### PR TITLE
[CFM-1198] Create Suggested projects block

### PR DESCRIPTION
**Pull request by DavidHernandez**
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1198
### Desktop

projects-desktop
### Tablet

projects-tablet
### Mobile

projects-mobile

### CODE REVIEW

**Comment by ordavidil** [comment]
@DavidHernandez 
Please just verify again that the block is seeing on the exact cases it should.

I want to avoid getting the same reject as in
https://issuetracker.amplexor.com/jira/browse/CFM-1061

**Comment by ybaras** [comment]
**Desktop**

fp

**Comment by ybaras** [comment]
**Tablet**

tab

**Comment by ybaras** [comment]
**Mobile**

mobile

**Comment by ybaras** [comment]
@ordavidil Ready for review.

**Comment by ordavidil** [comment]
@ybaras 
Please verify Diane's comment on: https://issuetracker.amplexor.com/jira/browse/CFM-1061
> For visitor, this block is displayed twice - both when there are featured groups the visitor can access + when there are no groups (the titles remain)

I know you've handled the first one, but please make sure the second one is done as well

**Comment by ybaras** [comment]
**Logged in user**

**Comment by ybaras** [comment]
**Visitor, No groups are featured in the system**

anon

**Comment by ybaras** [comment]
**Visitor**

anon2

**Comment by ordavidil** [comment]
@ybaras 

https://travis-ci.org/capacity4dev/capacity4more/jobs/170765337#L8710

job__7126_1_-_capacity4dev_capacity4more_-_travis_ci

**Comment by ordavidil** [comment]
Closing in favor of #1543

**Pull request closed without merging**
