### PR TITLE
CFD-387 : Group management Categories : Add/Update/Delete Category terms.

### PR DESCRIPTION
**Pull request by nader77**
#596

### CODE REVIEW

**Comment by nader77** [comment]
Workflow of adding a new term:
add_term

**Comment by nader77** [comment]
Note: After adding a new term, I just refresh the page, Update me if there's need to add it to the draggable table in javascript (AngularJs).

**Comment by nader77** [comment]
Update: Added term delete functionality:
delete_term

**Comment by nader77** [comment]
Update: Added reset alphabetical functionality:
reset

**Comment by nader77** [comment]
Note: The add term form is generated with form API as can be seen [here](https://github.com/capacity4dev/capacity4more/pull/597/files#diff-d599d7ebec10149d8f75d3d4f06c3e02L438)
The creation of the term is done with RESTful. (through AngularJs)

**Comment by nader77** [comment]
@HelenaEksler PR is ready for code review.

**Comment by HelenaEksler** [comment]
@nader77 Looks good. Let's merge it into the parent branch.

**Pull request merged**
