### PR TITLE
CFM-1137 - Update group activity stream (reviewed)

### PR DESCRIPTION
**Pull request by ybaras**
https://issuetracker.amplexor.com/jira/browse/CFM-1137

### CODE REVIEW

**Comment by ybaras** [comment]
capacity4more

**Comment by ybaras** [comment]
capacity4mor2e

**Comment by ybaras** [comment]
downed

**Comment by ybaras** [comment]
@ordavidil Screenshots added.

**Comment by soniCaH** [comment]
screen shot 2016-08-10 at 16 29 18
@ybaras icons still floating, please align them at the bottom for photo/photoalbum

**Comment by soniCaH** [comment]
Ok for photos, but icons still float for photoalbums:

screen shot 2016-08-29 at 15 38 44
screen shot 2016-08-29 at 15 40 11

**Pull request merged**
