### PR TITLE
CFD-536 Search : Articles & projects are not group content.

### PR DESCRIPTION
**Pull request by HelenaEksler**
https://issuetracker.amplexor.com/jira/browse/CFD-536

### CODE REVIEW

**Comment by HelenaEksler** [comment]
selection_339
selection_340

**Comment by HelenaEksler** [comment]
@nader77 Review this, please.

**Comment by HelenaEksler** [comment]
@nader77 Removed duplication.

**Comment by nader77** [comment]
@HelenaEksler Looks good, Assign to Amplexor when green.

**Pull request merged**
