### PR TITLE
cfd 265 theming date display in content listings

### PR DESCRIPTION
**Pull request by jummonk**

### CODE REVIEW

**Comment by jummonk** [comment]
library list
library table

**Comment by jummonk** [comment]
date in discussion teaser
date in discussion teaser

date in event teaser
date in event teaser

non recent date in document teaser
non recent date in document teaser

recent date in document teaser
recent date in document teaser

**Comment by zero2one** [comment]
needs a re-roll

**Comment by zero2one** [comment]
re-rolled

**Comment by zero2one** [comment]
re-rolled.

**Pull request merged**
