### PR TITLE
CFD-295 : Homepage : Video about Groups (Logged-in users).

### PR DESCRIPTION
**Pull request by nader77**
#505

### CODE REVIEW

**Comment by nader77** [comment]
@zero2one What i did is use YouTube's logic to display a thumbnail image of the video itself in the preview which will open a modal with the video:
homepage___capacity4more

The text above the video is also customizable.
Please update me if it's ok or i should use a static image, So i can finish it on sunday. Thanks.

**Comment by nader77** [comment]
groups

**Comment by zero2one** [comment]
@nader77 I can image that they want more control on the image used and not rely on the YouTube preview image.
Can you change it so they can set the static image?

**Comment by nader77** [comment]
Improve video preview: 
selection_065

**Comment by nader77** [comment]
@HelenaEksler Ready for code review.

**Comment by HelenaEksler** [comment]
@nader77 
Due to design https://projects.invisionapp.com/d/main#/console/2556061/57063329/preview video should be smaller:
mdz7bqz8mr

**Comment by nader77** [comment]
@HelenaEksler Sorry, needed to change the padding.
It's pixel-perfect now:

**Comment by HelenaEksler** [comment]
Can't see the screenshot/

**Comment by HelenaEksler** [comment]
@nader77 Looks ok. Assign to Peter when tests are green.

**Comment by nader77** [comment]
@zero2one PR is ready.

**Pull request merged**
