### PR TITLE
CFD-344 : Title is too short

### PR DESCRIPTION
**Pull request by nader77**
#618

### CODE REVIEW

**Comment by nader77** [comment]
"Title is too short" Was changed to appear only on form submitting, without showing when typing the title or losing focus from the input, Workflow:
qp-label-2015-04-08_16

**Comment by nader77** [comment]
PR is ready.

**Comment by zero2one** [comment]
The fix has:
* Broken the drag-n-drop of files
* Broken te widget when a file is uploaded trough the browse link

c4m-quick-post-problem

**Comment by nader77** [comment]
We fixed the document upload in #629, Need to wait for that branch to be merged to check if that fixes the issue.

**Comment by nader77** [comment]
@zero2one After merging develop the issue was fixed.
drag-upload-2015-04-21_14

**Pull request merged**
