### PR TITLE
WIP: CFD-285 : Homepage : Voices & views carousel 

### PR DESCRIPTION
**Pull request by nader77**
#468

### CODE REVIEW

**Comment by nader77** [comment]
Update: Added an angularJs carousel, That works with swipe (Mobile friendly), has buttons and arrows, Updating the design of the arrows and the bullets a bit to be seen, and adding text on the slides:
capacity4more

**Comment by nader77** [comment]
Added some design for the buttons and arrows so it can be seen, Video of the carousel:
Note: The mouse swipes equals for finger swipe on the mobile (Tested).
slide

**Comment by nader77** [comment]
Note: This will not show upon install until homepage is merged in and this plugin added to the homepage.

**Comment by nader77** [comment]
@zero2one Should i close this and open against ``develop`` ?

**Comment by zero2one** [comment]
Ah, missed this one.

@nader77 Yes please! 

Thanks.

**Comment by nader77** [comment]
Closed in favor of #481

**Pull request closed without merging**
