### PR TITLE
CFD-486 filter 'my groups' does not filter only my groups

### PR DESCRIPTION
**Pull request by HelenaEksler**
https://issuetracker.amplexor.com/jira/browse/CFD-486

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@nader77 Please, review.

**Comment by nader77** [comment]
@HelenaEksler Add a workflow video please.

**Comment by HelenaEksler** [comment]
video17

**Comment by MPParsley** [comment]
Looks fine except on the homepage when testing with new user. Steps to reproduce:
- create new user testuserfilter
- log in as user testuserfilter
- visit site homepage and wait
After some time the following message appears: "Error loading activity stream."

error loading activity stream

**Comment by HelenaEksler** [comment]
@MPParsley Can't reproduce the error. Waited for 10 minues both as new user without group and as president user that also doesn't have groups.

**Pull request merged**
