### PR TITLE
CFD-576 Wiki : add button to create subpage

### PR DESCRIPTION
**Pull request by HelenaEksler**
https://issuetracker.amplexor.com/jira/browse/CFD-576

### CODE REVIEW

**Comment by HelenaEksler** [comment]
PR is related to #731.
Workflow:
wiki

**Comment by HelenaEksler** [comment]
@nader77 Review, please.

**Comment by nader77** [comment]
@HelenaEksler Looks good, Assign to Peter when it's green.

**Comment by zero2one** [comment]
@HelenaEksler  needs a re-roll to fix the broken build

**Comment by HelenaEksler** [comment]
@zero2one Can be merged into the parent PR's branch.

**Comment by zero2one** [comment]
The platform does not allow creating levels deeper then 5 (is configured like that).

@HelenaEksler 
Hide the Add sublevel page when the current page is on sublevel 5.

Levels:
0 : The book (= group)
1 : The main wiki pages of the group (0 > 1)
2 : Subpage (0 > 1 > 2)
3 : Subpage (0 > 1 > 2 > 3)
4 : Subpage (0 > 1 > 2 > 3 > 4)
5 : Subpage (0 > 1 > 2 > 3 > 4 > 5)

**5 Is the maximum depth.**

**Comment by nader77** [comment]
Removed link for adding sub page on the 5th level.
selection_136
selection_135

**Comment by nader77** [comment]
@zero2one PR is ready.

**Pull request merged**
