### PR TITLE
CFD-259 : Quick Post : add the location name to the event form 

### PR DESCRIPTION
**Pull request by HelenaEksler**
#407

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@amitaibu Pr is ready for the code review.

**Comment by HelenaEksler** [comment]
selection_172

**Comment by zero2one** [comment]
@HelenaEksler 

Needs a re-roll.

**Comment by zero2one** [comment]
@HelenaEksler 

The form is not loading on the group hub page.

I get following js error in the console:

```
angular.js:9778 ReferenceError: scope is not defined
    at initFormValues (http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/c4m-app/dist/c4m-app.js?nih4fm:567:7)
    at new <anonymous> (http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/c4m-app/dist/c4m-app.js?nih4fm:571:5)
    at d (http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/angular/angular.min.js?nih4fm:34:265)
    at Object.instantiate (http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/angular/angular.min.js?nih4fm:34:394)
    at http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/angular/angular.min.js?nih4fm:66:112
    at http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/angular/angular.min.js?nih4fm:53:14
    at q (http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/angular/angular.min.js?nih4fm:7:386)
    at J (http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/angular/angular.min.js?nih4fm:52:382)
    at f (http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/angular/angular.min.js?nih4fm:46:399)
    at http://capacity4more.dev/profiles/capacity4more/libraries/bower_components/angular/angular.min.js?nih4fm:46:67
```

c4m-dashboard-error

**Comment by HelenaEksler** [comment]
@zero2one Fixed this bug [here](https://github.com/capacity4dev/capacity4more/commit/e21938415ae3da0278d2b78029c9048497f6c563). Re-installed project and don't see any errors.
selection_174

**Comment by HelenaEksler** [comment]
@zero2one Tests are green. Travis failed because of this:
selection_177

**Pull request merged**
