### PR TITLE
Replace callback function for message params, with their resolved value.

### PR DESCRIPTION
**Pull request by anvmn**
Code from #1613

### CODE REVIEW

**Comment by ordavidil** [comment]
@anvmn 
it seems that not all messages are covered, search for `message_create(` and catch the rest of the scenarios as well ...

**Comment by anvmn** [comment]
@ordavidil 
I found one place here: https://github.com/capacity4dev/capacity4more/pull/1614/commits/bf77dee650dc37623b8ec2bbddeacbceba3a3cd0#diff-a48c9f232aa5ef72e9f1d837774655daL1068

Did you see others?

**Comment by ordavidil** [comment]
@anvmn - here's a simple diff:

selection_350

### VS

selection_351


so just make sure we cover it all ...

**Comment by anvmn** [comment]
@ordavidil 
There are messages created for activity streams.They are not related to notification system.
Notifications message are concentrated at c4m_user_notifications_handlers.inc file.

As I see it, all messages are covered.

**Comment by ordavidil** [comment]
The issue is for all created messages, not only notifications ...

**Comment by soniCaH** [comment]
@ordavidil 

screen shot 2016-12-09 at 14 26 37

**Pull request merged**
