### PR TITLE
CFD-522 Image styles : Define the default image styles.

### PR DESCRIPTION
**Pull request by nader77**
https://issuetracker.amplexor.com/jira/browse/CFD-522

### CODE REVIEW

**Comment by nader77** [comment]
Image styles: 
selection_114

**Comment by nader77** [comment]
@HelenaEksler Please review this.

**Comment by HelenaEksler** [comment]
@nader77 Looks good.

**Comment by HelenaEksler** [comment]
@MPParsley PR is ready for review.

**Comment by soniCaH** [comment]
Sizes are correctly, but image styles are listed as "overridden". Is there a way to prevent this?

screen shot 2015-05-13 at 18 02 27

**Comment by nader77** [comment]
@soniCaH I have created this PR according to the description in the issue step by step, Tried to revert the ``override`` but i don't have enough time to investigate and search for a solution.
One small correction to the ``small`` image style has improved the code.

This is ready for code review again.

**Comment by MPParsley** [comment]
@nader77, these image styles are provided by Drupal core in the core image module (see image_image_default_styles).
They can easily be overridden using hook_image_styles_alter(), see https://api.drupal.org/api/drupal/modules!image!image.api.php/function/hook_image_styles_alter/7

**Comment by MPParsley** [comment]
schermafdruk 2015-05-14 22 41 56

**Pull request merged**
