### PR TITLE
CFD-561 : Theming article detail page.

### PR DESCRIPTION
**Pull request by nader77**
https://issuetracker.amplexor.com/jira/browse/CFD-561

### CODE REVIEW

**Comment by nader77** [comment]
Contribution users theming: 
2004_indian_ocean_earthquake_and_tsunami___capacity4more

**Comment by nader77** [comment]
@HelenaEksler Please review.

**Comment by HelenaEksler** [comment]
@nader77 Looks good as for me. Will wait for final design of the page before merge I think. When test are green - Assign to Peter with question should we change the color of font or whatever due to design when it's ready.

**Comment by MPParsley** [comment]
removed left margin from username in contributors list:

schermafdruk 2015-05-18 08 38 39

**Pull request merged**
