### PR TITLE
Main widgets

### PR DESCRIPTION
**Pull request by nader77**
This PR contains all the changes we made to the widgets in the full form.
This will be the final PR to merge, All the work is merged to the branch and tested here.

### CODE REVIEW

**Comment by nader77** [comment]
Merged to this branch is the following PRs:
#328
#333 

The following branches are merged to #333:
#315 
#326 (which branches out from #324 and #322 )

**Comment by amitaibu** [comment]
This mega branch is a consolidation of all the PR we've worked on during your holidays. In order not to chase head, and be able to make sure all PRs are working nicely with each other.
All the code was reviewed in the single PRs, and when passed tests was merged here. 

@zero2one t If you can test it, and merge to ``develop`` it would be great

**Comment by zero2one** [comment]
Can you list the Jira tickets that are included in this mega PR?

**Comment by nader77** [comment]
* CFD-173
* CFD-174
* CFD-205
* CFD-206
* CFD-207
* CFD-208
* CFD-210
* CFD-211
* CFD-212
* CFD-241

There's some work that is not logged yet, Will log today.

**Comment by zero2one** [comment]
CFD-205 : OK

**Comment by zero2one** [comment]
CFD-208 : OK

**Comment by zero2one** [comment]
CFD-210 : NOT OK (Discussion full form)

Form elements are not in the proper order.
cfd-210_dicussion_full_form

  
Desired field order:
  - Title
  - Type of discussion
  - Description
  - Documents
  - Topics
  - Group categories
  - Date
  - Language
  - Regions & Countries
  - Tags

**Comment by amitaibu** [comment]
@zero2one I think it's worth opening this as follow-ups, in order to avoid working directly on this mega branch. What do you think?

**Comment by zero2one** [comment]
CFD-211 : NOT OK (Full form : Document)
  
Form elements are not in the proper order.
cfd-211_document_full_form

  Desired field order:
  - Document (file upload)
  - Title
  - Description
  - Type of document
  - Topics
  - Group Categories
  - Date
  - Language
  - Regions & Countries
  - Tags

**Comment by zero2one** [comment]
CFD-212 : Full form : Events

I get a white page : HTML is loaded but not rendered (Chrome/Firefox/Safari).

**Comment by zero2one** [comment]
We could do that but my previous comment (White screen on event forms) should be fixed as this breaks functionality.

**Comment by amitaibu** [comment]
@zero2one thanks
@nader77 please look at the WSOD (probably a JS error, and ``ng-cloak`` hiding the page?)

**Comment by nader77** [comment]
@zero2one I know this error, This is a problem in your ``getlocation`` module markers cache, Could you please clean the cache from the admin menu and try again ?

**Comment by nader77** [comment]
Event create page:
selection_054

**Comment by zero2one** [comment]
Clearing the event cache fixes the white screen.

**Comment by zero2one** [comment]
CFD-212 : Full form : Events

Form elements are not in the proper order.
cfd-212_event_full_form


  
  The file upload fields (Agenda & Information, Presentations, Additional) 
  should be also replaced by the file field widget (browse, drop, select from 
  library).
  
  Desired field order:
  - Title
  - Type of event
  - Description
  - Organised by
  - Event website
  - Facebook page
  - Twitter page
  - When
    - Start date/time
    - End date/time
  - Where
    - Name (venue name)
    - Street & number
    - Postal code
    - City
    - Country
  - Documents
    - Agenda & informaton
    - Presentations
    - Additional
  - Topics
  - Categories
  - Language
  - Regions & Countries
  - Tags

**Comment by zero2one** [comment]
CFD-206 : NOK (Field widgets : Select Regions & Countries)

Possible to select countries without the parent region.

c4m-taxonomy-region-country

c4m-taxonomy-region-country

  

  Scenario:
  - Create new discussion.
  - Select "7. EU Member states"
  - Select "Belgium", "Bulgaria", "Croatie"
  - Close the checkbox popup.
  - Remove "7. EU Member states"
  - Save 
  > The EU memberstate is not listed (OK)
  > "Belgium", "Bulgaria", "Croatie" are listed (NOK)
  > Desired: removing the parent region should also remove the child countries.

**Comment by zero2one** [comment]
CFD-207 : NOK (Field widgets : Select Type of document)

Same problem as [CFD-206](https://github.com/capacity4dev/capacity4more/pull/334#issuecomment-68987847)

**Comment by amitaibu** [comment]
@HelenaEksler ^^

**Comment by zero2one** [comment]
CFD-212 : Full form

@HelenaEksler The file fields are replaced by the file widgets => OK

But the field titles are missing
c4m-event-form-files

**Comment by zero2one** [comment]
CFD-173 : OK (Field widgets : File upload widget)

**Comment by zero2one** [comment]
There are no blocking issues. I will create tasks for follow up actions.

**Pull request merged**
