### PR TITLE
CFD-460 : Comments are not truncated on the homepage activity stream

### PR DESCRIPTION
**Pull request by solker**
For comment inside next content types : 
* discussion
* event
* photo
* photoalbum
* document
* wiki_page
* task
* tasklist
* article

Applied trim options equal 300 characters.
selection_011

### CODE REVIEW

**Comment by solker** [comment]
@HelenaEksler PR is ready for code review.

**Comment by HelenaEksler** [comment]
@zero2one PR is ready for review.

**Comment by HelenaEksler** [comment]
@solker Please, move each feature to relevant content type module.

**Comment by solker** [comment]
@MPParsley @HelenaEksler solved in another branch #703. This closed.

**Pull request closed without merging**
