### PR TITLE
CFM-969: Open following for all users

### PR DESCRIPTION
**Pull request by DavidHernandez**
Allows authenticated users to follow/unfollow groups and projects

Issue: https://issuetracker.amplexor.com/jira/browse/CFM-969

### CODE REVIEW

**Comment by jover** [comment]
How to test this? I see only permissions in the change logs...

**Comment by ordavidil** [comment]
@DavidHernandez 
is there any change on the display for that ?
or maybe configuration that we can see at the admin ?

**Comment by DavidHernandez** [comment]
@ordavidil @jover the issue only talks about the "follow" action to be available for all users. There is a different PR / Issue related with this one where the link is actually added and there can be tested that the link works for all the users: https://github.com/capacity4dev/capacity4more/pull/1110

So yes, maybe we have to merge the other PR first in order to be able to test this.

**Comment by ordavidil** [comment]
@DavidHernandez 
it seems like #1110 should've compared with the current branch of this PR (like a dependency)

**Pull request merged**
