### PR TITLE
CFD-378: Group approval workflow : Show status in header of group pages.

### PR DESCRIPTION
**Pull request by nader77**
#539

### CODE REVIEW

**Comment by nader77** [comment]
Status field next to the title of the group:
capacity4more

**Comment by nader77** [comment]
Some other statuses:

selection_074

selection_075

**Comment by nader77** [comment]
Update: Changed the ``OG`` module version because @HelenaEksler's PR has been merged to the main branch.

**Comment by nader77** [comment]
@HelenaEksler Status is shown always expect when group's status is "Published".
PR is ready for code review.

**Comment by HelenaEksler** [comment]
@nader77 Looks fine.

**Pull request merged**
