### PR TITLE
CFD-529 Group library: Add the functionality to upload document(s) when adding a comment.

### PR DESCRIPTION
**Pull request by HelenaEksler**
https://issuetracker.amplexor.com/jira/browse/CFD-529

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@zero2one @MPParsley I need some info how comment with document should look like in the activity stream (on group dashboard and on site homepage).

**Comment by HelenaEksler** [comment]
Update:
comment

**Comment by HelenaEksler** [comment]
Homepage activity stream:
selection_335
Group activity stream:
selection_336
In commented content:
selection_337
Comment full view (when press reply):
selection_338

**Comment by HelenaEksler** [comment]
@nader77 Review, please.

**Comment by nader77** [comment]
@HelenaEksler Looks good, Assigning to Peter.

**Comment by zero2one** [comment]
@HelenaEksler needs a re-roll

**Comment by zero2one** [comment]
@HelenaEksler  needs a re-roll to fix the broken build

**Comment by zero2one** [comment]
Everything tested within the nobelprize group.

### Adding comments with documents as platform administrator
Adding a comment to /nobelprize/document/nobel-prize-ceremony
* :white_check_mark: Select from library 
* :white_check_mark: Upload and add to library
* :white_check_mark:  Upload and not add to library

### Adding comments with documents as group administrator
Adding a comment on /nobelprize/document/nobel-prize-ceremony
* :white_check_mark: Select from library
* :x: Upload and add to library 
* :x: Upload and not add to library

**Problem** : The popup opens when uploading a file but when hitting "Yes" or "No" results in 400 Bad request in console.
c4m-comment-document


### Adding comments with documents as group member
Adding a comment on /nobelprize/document/nobel-prize-ceremony
* :white_check_mark: Select from library
* :x: Upload and add to library 
* :x: Upload and not add to library

**Problem** : The popup opens when uploading a file but when hitting "Yes" or "No" results in 400 Bad request in console.
c4m-comment-document

**Comment by nader77** [comment]
@HelenaEksler I debugged this, There something changed in the code that prevents the operation 'view' on the group property, It passes for admin because when there's no entity, it returns true only for admin.

non-platform admins or normal members can't post even in the QP.

**Comment by nader77** [comment]
@zero2one The problem was with changing the version of the ``entity`` module and removing the Patch needed for Restful to work.
After restoring this, It fixed the permission for non-platform admin users to create entities through restful.
upload-document-comment

**Comment by nader77** [comment]
Please note that the QP won't have the correct permission as until this branch + #660 are merged.

**Pull request merged**
