### PR TITLE
CFD-510 : Restrict access to the create content based on the group context.

### PR DESCRIPTION
**Pull request by solker**
https://issuetracker.amplexor.com/jira/browse/CFD-510

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@nader77 Please, check.

**Comment by nader77** [comment]
@HelenaEksler Looks good, Add screenshot/gif if possible.

**Comment by HelenaEksler** [comment]
access_denied___capacity4more-5
barclays_atp_world_tour_finals___capacity4more-3
access_denied___capacity4more-3

**Comment by zero2one** [comment]
@solker  needs a re-roll to fix the broken build

**Comment by solker** [comment]
@zero2one re-rolled. Waiting Travis.

**Comment by soniCaH** [comment]
Opened #794

**Pull request closed without merging**
