### PR TITLE
CFD-429 : Quickpost to full form -> file upload fail

### PR DESCRIPTION
**Pull request by nader77**
https://issuetracker.amplexor.com/jira/browse/CFD-429

### CODE REVIEW

**Comment by nader77** [comment]
Fix workflow:
upload-document

**Comment by nader77** [comment]
@HelenaEksler PR is ready for code review.

**Comment by HelenaEksler** [comment]
@nader77 Looks ok.

**Comment by HelenaEksler** [comment]
@nader77 Move to the proper column in Jira as well.

**Pull request merged**
