### PR TITLE
[CFM-1031] -Set up right permissions for invite functionality

### PR DESCRIPTION
**Pull request by ybaras**
https://issuetracker.amplexor.com/jira/browse/CFM-1031

### CODE REVIEW

**Comment by ybaras** [comment]
@ordavidil I did not end up using code from the `feature/CFM-1206-group-actions` for this PR, should I merge and pull request to develop instead?

**Comment by ordavidil** [comment]
@ybaras 
Did you omean __close__ ?

**Comment by ybaras** [comment]
@ordavidil no, I meant re-roll from develop before creating a PR to avoid conflicts and **then** close :smile: .

**Comment by ybaras** [comment]
**Invite links:**

invite

**Invite other users"**

invite-users

**Invite people by email (and create users):**

invite-people

**Comment by ybaras** [comment]
New PR: #1113

**Pull request closed without merging**
