### PR TITLE
Separate the AngularJs App controllers.

### PR DESCRIPTION
**Pull request by nader77**
#327 
* Created a new controller called "Activity". (This will eliminate any unnecessary calls to activity-stream)
* Created a broadcast that communicates between the 2 controllers.
* Fixed the scroll when creating a new activity.
* Optimized the code in the main controller, Because we need to call it in many places, this will make it faster to load.

Adding new activity with the new fixes:
activity

### CODE REVIEW

**Comment by nader77** [comment]
Update: optimized the refresh functions to avoid any conflicts between the normal refresh of the activity stream and the data pull of creating a new Activity.

**Comment by nader77** [comment]
@amitaibu This PR is ready for code review.

**Comment by amitaibu** [comment]
Please open PR against ``develop-widgets``, and close this.

**Comment by nader77** [comment]
This is merged into ``develop-widgets``

**Pull request closed without merging**
