### PR TITLE
[CFM-558] auto subscribe content commentors for notifications

### PR DESCRIPTION
**Pull request by anvmn**
## This PR is dependent on #1095 

https://issuetracker.amplexor.com/jira/browse/CFM-558

### CODE REVIEW

**Comment by anvmn** [comment]
@ordavidil 
Might need to be moved to  'user subscribe' model.

**Comment by ordavidil** [comment]
@anvmn 
I think it's clear now what should be done ...

**Comment by anvmn** [comment]
@ordavidil 
Right, but we wanted to concentrate all subscription at one module, that is introduced at https://github.com/capacity4dev/capacity4more/pull/1115.
I can open a new branch from #1115, and add functionality there, or wait for #1115 to be merged.
Which one do you prefer?

**Comment by ordavidil** [comment]
@anvmn 
please checkout from that branch ...

**Comment by anvmn** [comment]
Closing in favor of #1204

**Pull request closed without merging**
