### PR TITLE
CFD-525 : Wiki : Make the sidebar collapsible + theme content

### PR DESCRIPTION
**Pull request by nader77**
https://issuetracker.amplexor.com/jira/browse/CFD-525

Workflow:
collapse-sidebar-2015-05-11_12

### CODE REVIEW

**Comment by nader77** [comment]
@HelenaEksler Please review this.

**Comment by HelenaEksler** [comment]
@nader77 Looks good.

**Comment by nader77** [comment]
Theme:
collapse

@MPParsley I have added as much theming as i can with the time i had for this issue, For full theming there should be a new issue with the appropriate time estimation.

**Comment by MPParsley** [comment]
In mobile view the side navigation overlaps the page title:
wiki mobile sidenav

Sidebar is not themed like the design:
wiki sidebar design
wiki sidebar implementation

**Comment by nader77** [comment]
Update: Fixed sidebar in mobile
selection_128

**Comment by zero2one** [comment]
@nader77  needs a re-roll to fix the broken build

**Comment by nader77** [comment]
@zero2one I merged from develop, No need to re-roll or fix anything.

**Comment by nader77** [comment]
Sidebar:
sidebar-2015-05-28_12

**Pull request merged**
