### PR TITLE
[CFM-374-fix] Do not update group content realms when group request is approved/rejected.

### PR DESCRIPTION
**Pull request by anvmn**
https://issuetracker.amplexor.com/jira/browse/CFM-374

### CODE REVIEW

**Comment by anvmn** [comment]
anim

**Comment by ordavidil** [comment]
@anvmn 
will we have access issues after this?
please verify with all roles (SA/GO/ etc.)

**Comment by anvmn** [comment]
@ordavidil 
There  `c4m_og_handle_group_status_change()` was added at https://github.com/capacity4dev/capacity4more/pull/1634.
It assigns group realms to group content, when group status changes.
This was done to present correct content at views, if  I remember correctly.
As 'pending' group got no content, there's no need to execute the function.

Don't see access issue here.

**Comment by soniCaH** [comment]
@anvmn do I understand this remark correctly?

> As 'pending' group got no content, there's no need to execute the function.

It is possible to add content to a pending group, to "prepare" it before being approved. So by the time a group is approved, it is possible it has already plenty of content.

**Comment by ordavidil** [comment]
@soniCaH 
As I remember from talks with Diane, content can not be added to a pending group, but only to a draft one.

**Comment by soniCaH** [comment]
@ordavidil the draft status was replaced by pending when we started this phase.
When you request a new group, you are able to add content.

**Comment by ordavidil** [comment]
@soniCaH not sure this is right, as I remember (and this one pretty good), _pending_ replaced the _requested_ status.

**Comment by soniCaH** [comment]
@ordavidil seems right. Must have tested it with mariecurie which is a SA then.
Bless your memory.

The only potential issue is a SA adding content to a pending group before approving it then?

**Comment by ordavidil** [comment]
Which is very strange situation that should not happen.

**Comment by ordavidil** [comment]
I think we also discussed about this with Diane if I remember correctly - specifically about SA adding content to pending group,  @anvmn do you remember this conversation >

**Comment by anvmn** [comment]
@soniCaH 
We had a discussion about this with Diane, and final decision was that no one is allowed to add content to pending group. Not even site admin.
Final permissions summary:
selection_476

**Comment by soniCaH** [comment]
@anvmn I see, the issue mainly is that the "add document", "add event" buttons + "quickpost"... are all shown in a pending group.

**Comment by soniCaH** [comment]
screen shot 2017-02-22 at 18 13 59

**Comment by ordavidil** [comment]
@soniCaH 
The buttons will lead to access denied - which is fine.

@anvmn 
Check the quickpost again, if needed then make the changes in the `checkEntityAcess()` under the `C4mRestfulEntityBaseNode` class (_c4m_restful_ module).

**Comment by anvmn** [comment]
@ordavidil 
I see that admin can create a discussion via quick post.
I think that if such action is not allowed, QP form should not be visible at all.
If I'm not mistaken, that is what we do when user may not post with QP create group content.

**Comment by ordavidil** [comment]
@soniCaH 
It seems like a sufficient solution for me,  please confirm.

**Comment by ordavidil** [comment]
@soniCaH ^^

**Comment by soniCaH** [comment]
@ordavidil @anvmn agreed.

**Comment by ordavidil** [comment]
@anvmn 
please open a new PR for that.

**Pull request merged**
