### PR TITLE
CFM-1390 registration form fixes

### PR DESCRIPTION
**Pull request by anvmn**

### CODE REVIEW

**Comment by anvmn** [comment]
https://issuetracker.amplexor.com/jira/browse/CFM-1390

**Comment by anvmn** [comment]
selection_056

**Comment by anvmn** [comment]
@or ready for review

**Comment by amitaibu** [comment]
Looks good.

**Comment by soniCaH** [comment]
@anvmn can you please limit "Topics of Expertise" to 3 level-1 topics, like "Topics of Interest"?

**Comment by amitaibu** [comment]
@soniCaH , dude aren't you supposed to be enjoying Milano right now instead of doing reviews? 😉

**Comment by soniCaH** [comment]
I've got my flight in a few hours 👍

**Comment by anvmn** [comment]
@soniCaH 

The limitation for 3 level 1 is set for expertise as well:

...dules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js : 
 else {
            // Check up to 3 topics selected.
          if (vocab == 'c4m_vocab_topic' || **vocab == 'c4m_vocab_topic_expertise'** || vocab == 'c4m_vocab_geo') { ...

**Comment by anvmn** [comment]
@ordavidil 
Problem with c4m_app.js, that is not being copied to correct location.

**Pull request merged**
