### PR TITLE
CFD-369: In the picture : create new content type

### PR DESCRIPTION
**Pull request by nader77**
#535 

Added the content type and the module.
selection_066

selection_067

@zero2one There's a text field called ``c4m_page`` which is a text field, I want a select list field for this content type, Right ?
If yes, What should i call it ? (Now it's ``field_page``),

### CODE REVIEW

**Comment by nader77** [comment]
Update: Added demo migration to the content type:

* Nodes created in the demo migration:

selection_068

* Node edit form (Filled fields):
selection_069

**Comment by zero2one** [comment]
@nader77 
* Set the label of that field to: "Overview page"
* Set the description of the field to: "Select the overview page where this in the picture item should be shown."

The multiple checkboxes are ok.

**Comment by nader77** [comment]
@zero2one Field machine name ``c4m_overview_page`` is ok ?

**Comment by zero2one** [comment]
@nader77 yes

**Comment by HelenaEksler** [comment]
@nader77 Is it ready? If so - assign to Peter.

**Pull request merged**
