### PR TITLE
CFD-311 : Homepage: Add video to header about "what is C4D"

### PR DESCRIPTION
**Pull request by nader77**
#475

### CODE REVIEW

**Comment by nader77** [comment]
Update: Added a plugin for the video link:

1- Add the plugin to wherever we want + add the Video's share url:
selection_032

2- The button of opening the video:
selection_029

3- The video in Modal:
selection_030

**Comment by nader77** [comment]
Update: "Embed video" is a generic plugin, It can be added every where, It will render a button (Text on the button is configurable) and an embedded YouTube video that user can enter it's share/ regular URL.

Workflow:
video-2015-02-11_10
video-2015-02-11_11

**Comment by nader77** [comment]
Update: Video window is responsive:
video-2015-02-11_12

**Comment by nader77** [comment]
@HelenaEksler PR is ready for code review.

**Comment by HelenaEksler** [comment]
@nader Video is not paused when I close the modal window.

**Comment by nader77** [comment]
Closed in favor of #488

**Pull request closed without merging**
