### PR TITLE
CFD-356 : Group Categories

### PR DESCRIPTION
**Pull request by solker**
Hide empty categories in Group Categories widget

https://issuetracker.amplexor.com/jira/browse/CFD-356

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@solker Looks fine.

**Comment by zero2one** [comment]
Does not work as expected:
* I log in as admin
* I go to the nobelprize group
* A go the management of the group
* I go the category types
* I add a new category type "Empty category type", I do not add terms to it.
* I go to the discussion full form
* I click on the Categories button

:x:  "Empty category type" is shown.

cfd-356

**Comment by solker** [comment]
@zero2one fixed for full template.

**Comment by soniCaH** [comment]
"The implementation that appears for a brand new Group (blank window) should be applied when there are no Group Category tags (perhaps with a small message to say none have been defined."

screen shot 2015-05-13 at 13 00 40

**Comment by nader77** [comment]
No categories message:

In full form:
edit_discussion_test___capacity4more

In QP:
capacity4more

**Comment by nader77** [comment]
@HelenaEksler PR is ready for code review.

**Comment by HelenaEksler** [comment]
@nader77 Looks good. Send it to QC after tests would be green

**Comment by nader77** [comment]
@MPParsley @zero2one PR is ready for code review.

**Comment by MPParsley** [comment]
OK in full form, in QP as admin user the search field is still displayed:
group categories quickpost

**Comment by nader77** [comment]
@MPParsley Could you please re-install from the beginning and make sure the angularJs app is in it's latest version in the library.
I can't reproduce the bug:
selection_126

Tried all the existing groups and added a new one,
Tried with admin user and a regular user.

**Pull request merged**
