### PR TITLE
CFD-206 : Regions & Country widget should have 3 levels.

### PR DESCRIPTION
**Pull request by HelenaEksler**
#392 
#396

### CODE REVIEW

**Comment by HelenaEksler** [comment]
selection_166
selection_167

**Comment by HelenaEksler** [comment]
3levtax

**Comment by HelenaEksler** [comment]
@amitaibu PR is ready for the code review.

**Comment by zero2one** [comment]
I approved it as it fixes the issue and is needed for the sprint demo.

**Pull request merged**
